DENG-1120: Add statement_timeout parameter to Arthur Redshift cluster configuration
harrystech/arthur-redshift-etl pull request #586
Opened 2021-11-09 16:19 UTC by ynaim94

## Description

Adding to Arthur the possibility to set [statement_timeout](https://docs.aws.amazon.com/redshift/latest/dg/r_statement_timeout.html)  when running either Arthur load, upgrade or update. The parameter is setup in `resources.RedshiftCluster.statement_timeout` in the Arthur configuration file. The default 0 means to not timeout.

### User-visible Changes

Users can decide how long they want their query to run before cancelling them, either by setting `resources.RedshiftCluster.statement_timeout` or by passing the value as argument to `--statement-timeout` when running upgrade, updates and load with the Arthur CLI.

### Internal Changes

Arthur reads the configuration file to get the `statement_timeout` value. It will then run `set statement_timeout to {timeout}` everytime an  Arthur load, upgrade or update command is run, which includes all the ETL runs and commands used during development. I

## Links

https://harrys.atlassian.net/browse/DENG-1120

## Testing

## Deploy Notes

2021-11-10 17:47 UTC, thomas-vogels requested changes
Looks great overall. Small bug in `load` args.

Is there any performance impact? I'm assuming no since this is done per connection and not per relation. But I wanted to check.

2021-11-10 17:47 UTC, thomas-vogels commented on python/etl/load.py
> +          FROM {_table}
A leading underscore has a semantic meaning in Python. That's why appending an underscore is usually preferred. So `limit_` instead of `_limit`. 

> single_trailing_underscore_: used by convention to avoid conflicts with Python keyword, e.g.:

* Nice overview:
https://medium.com/python-features/naming-conventions-with-underscores-in-python-791251ac7097

2021-11-10 17:47 UTC, thomas-vogels commented on python/etl/commands.py
> +            metavar="N",
What is the unit for the timeout? (Seconds? Microseconds? Hours?)

Please add in the text. Or maybe you can use the `metavar` to keep the help text short?

Consider something like this (or **better**):
```diff
diff --git a/python/etl/commands.py b/python/etl/commands.py
index 248dc51..3e4931b 100644
--- a/python/etl/commands.py
+++ b/python/etl/commands.py
@@ -464,7 +464,7 @@ def add_standard_arguments(parser: argparse.ArgumentParser, option_names: Iterab
         parser.add_argument(
             "-t",
             "--statement-timeout",
-            metavar="N",
+            metavar="MILLISECS",
             type=int,
             help="set the timeout before canceling a statement in Redshift. This time includes planning,"
             " queueing in WLM, and execution time. (overrides "
```

With this output:
```
  -t MILLISECS, --statement-timeout MILLISECS
                              set the timeout before canceling a statement in Redshift. This time includes planning, queueing in WLM, and execution time. (overrides 'resources.RedshiftCluster.statement_timeout')
```

(Separately, the lowercase `overrides` looks funny after a period. But 🤷 )

2021-11-10 17:47 UTC, thomas-vogels commented on python/etl/commands.py
> +                "statement_timeout",
Careful, this needs to match the standard arg:
`statement_timeout` -> `statement-timeout`

2021-11-10 17:54 UTC, ynaim94 commented on python/etl/commands.py
> +                "statement_timeout",
Obviously the only one I didn't test 😅  Thanks, that saved us an ETL run.

2021-11-10 18:08 UTC, thomas-vogels commented
Do I see this correctly that this is best for interactive use?

For regular ETLs, I'm assuming that you'd I'd think that using a configuration file (`{"resources": {"RedshiftCluster": {"statement_timeout": ...}}`) is more maintainable. It's called out as "optional" but seems to be easier overall.

2021-11-10 18:12 UTC, ynaim94 commented
@thomas-vogels You mean in the deploy notes? I meant by that that it is an optional configuration, that Arthur would work even if the value is missing. Let me know if I'm misunderstanding.

2021-11-10 18:27 UTC, ynaim94 commented
> Is there any performance impact? I'm assuming no since this is done per connection and not per relation. But I wanted to check.

I didn't find anything talking about performance issues in the documentation. This will be ran once every connection is established (once every ETL then?).

2021-11-10 20:40 UTC, thomas-vogels approved these changes
LGTM -- Thanks!

2021-11-10 21:12 UTC, merged

2021-11-10 22:30 UTC, thomas-vogels commented
> > Is there any performance impact? I'm assuming no since this is done per connection and not per relation. But I wanted to check.
> 
> I didn't find anything talking about performance issues in the documentation. This will be ran once every connection is established (once every ETL then?).

Let's say you have 1000 relations and you add a step that takes 1 s. Now your ETL runs 15 minutes longer. So it's worth keeping in mind how additional changes affect the total ETL time.
Again, shouldn't be a problem here.

More important: Say the cluster has a timeout of 2 hours and I pass in a timeout of 0 using the new command line arg. Does the cluster setting still apply or would the query now run without a timeout?

2021-11-12 18:52 UTC, thomas-vogels commented on python/etl/commands.py
> +        )
So that feels like a surprise to users. My expectation as a user would be:
* If I specify the statement timeout on the command line, and that's used.
* If I specify the statement timeout in a settings file (and not on the command line), that's used.
* If there's nothing set on the command line or a settings file, the statement timeout from the cluster is used.

2021-11-12 18:56 UTC, ynaim94 commented on python/etl/commands.py
> +        )
Sounds good, I will open a PR to use the cluster setup if nothing is set.